source "https://rubygems.org"

group :development do
  gem 'rake'
  gem 'jekyll', '>= 4.0.0'
  gem 'octopress-hooks', '~> 2.2'
  gem 'octopress-date-format'
  gem 'jekyll-sitemap'
  gem 'rdiscount', '~> 2.0'
  gem 'RedCloth', '>= 4.3.0'
  gem 'haml', '>= 5.0.0'
  gem 'compass', '>= 1.0.1'
  gem 'sass-globbing', '>= 1.0.0'
  gem 'rb-fsevent', '~> 0.9'
  gem 'stringex', '~> 1.4.0'
end

gem 'sinatra', '~> 1.4.2'
